#
# CentOS 7 Dockerfile
#

# Pull base image
FROM centos:latest

RUN yum update -y && yum upgrade -y
RUN yum install -y unzip wget curl git
RUN yum install -y epel-release
RUN yum clean all
ENV HOME /root


#install ssh
RUN yum install -y openssh-server
RUN mkdir /var/run/sshd
RUN echo 'root:passwd123' | chpasswd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

# Working directory
WORKDIR /root

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]









