#
# Python Dockerfile
#
# https://github.com/dockerfile/python
#

# Pull base image.
FROM ubuntu:16.04

# Install Python.
RUN apt-get update
RUN apt-get install -y python python-dev python-pip python-virtualenv
RUN rm -rf /var/lib/apt/lists/*

#install flask
RUN pip install flask
ADD test_flask.py /root

#install ssh
RUN apt-get update && apt-get install -y openssh-server
RUN mkdir /var/run/sshd
RUN echo 'root:passwd123' | chpasswd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

# Define working directory.
WORKDIR /data

EXPOSE 22
EXPOSE 5000
CMD ["/usr/sbin/sshd", "-D"]

###### pending
### enable both sshd and flask app
#### run flask app using "python test_flask.py"
### app will run on exposed 5000 port in host localhost:exposed_port


